---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eleven-devops-deployment
  namespace: default
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: elevendevops-container
        image: bharaths987/docker_ci:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
 name: my-elevendevops-service
 namespace: default
 labels:
   app: my-app
spec:
 type: NodePort
 ports:
  - targetPort: 8080
    port: 8080
    nodePort: 30072
 selector:
   app: my-app

...
